---
version: '3'
services:
  tests:
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade-backtesting
    volumes:
      - "./:/testing"
    command: >
      python -m pytest -ra -vv -s --log-cli-level=info --artifacts-path=artifacts/ ${EXTRA_ARGS:-tests/}
    entrypoint: []
    working_dir: /testing
  backtesting:
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade-backtesting
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./NostalgiaForInfinityNext.py:/freqtrade/NostalgiaForInfinityNext.py"
    command: >
      backtesting
      --strategy-list ${STRATEGIES:-NostalgiaForInfinityNext NostalgiaForInfinityV1 SMAOffsetProtectOpt ElliotV2 ElliotV3}
      --timerange ${TIMERANGE:-20210508-20210608}
      --config user_data/data/pairlists.json
      --config user_data/data/${EXCHANGE:-binance}-usdt-static.json
      --max-open-trades ${MAX_OPEN_TRADES:-5}
      --stake-amount ${STAKE_AMOUNT:-unlimited}
  download-data:
    image: freqtradeorg/freqtrade:develop
    container_name: download-data
    volumes:
      - "./user_data:/freqtrade/user_data"
    command: >
      download-data
      --timerange ${START_DATE:-20210101}-${END_DATE:-20210729}
      --timeframe 5m 1h
      --datadir user_data/data/${EXCHANGE:-binance}
      --config user_data/data/pairlists.json
      --config user_data/data/${EXCHANGE:-binance}-usdt-static.json


  freqtrade:
    build:
       context: .
       dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./NostalgiaForInfinityNext.py:/freqtrade/NostalgiaForInfinityNext.py"
    ports:
       - "0.0.0.0:4406:4406"
    tty: true

